"""Encode two GLBs with multiview DINO/TRELLIS and sample a MorphFlow CFG grid.

alpha=1 selects src1; alpha=0 selects src2. All three alpha values are
generated by the model, including endpoints. GLBs use decoded vertex colors.
"""
import argparse
import gc
import hashlib
import itertools
import json
import math
import os
from pathlib import Path
import subprocess
import time

ENCODER = "slat_enc_swin8_B_64l8_fp16"
SS_DECODER = "ss_dec_conv3d_16l8_fp16"
MESH_DECODER = "slat_dec_mesh_swin8_B_64l8m256c_fp16"
REPO = "microsoft/TRELLIS-image-large"


def number_list(value):
    values = [float(x) for x in value.replace(",", " ").split()]
    if not values or any(not math.isfinite(x) for x in values):
        raise argparse.ArgumentTypeError("Expected a nonempty list of finite numbers")
    if len(set(values)) != len(values):
        raise argparse.ArgumentTypeError("Duplicate values in sweep")
    return values


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("src1", type=Path, help="First input GLB, selected at alpha=1")
    p.add_argument("src2", type=Path, help="Second input GLB, selected at alpha=0")
    p.add_argument("--ss-checkpoint", type=Path, required=True)
    p.add_argument("--slat-checkpoint", type=Path, required=True)
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--blender", type=Path, required=True, help="Blender 3.x executable")
    p.add_argument("--alphas", type=number_list, default=number_list("0,0.5,1"))
    p.add_argument("--cfg-ss", type=number_list, default=number_list("2,2.5,3"))
    p.add_argument("--cfg-slat", type=number_list, default=number_list("1.5,2,2.5"))
    p.add_argument("--steps", type=int, default=50)
    p.add_argument("--slat-steps", type=int, default=50)
    p.add_argument("--encoding-views", type=int, default=50)
    p.add_argument("--dino-batch-size", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--mixed-precision", choices=("bf16", "fp16", "no"), default="bf16")
    p.add_argument("--mode", choices=("run", "check", "prepare"), default="run")
    args = p.parse_args(argv)
    if any(a < 0 or a > 1 for a in args.alphas):
        p.error("alphas must be in [0,1]")
    if min(args.cfg_ss + args.cfg_slat) < 0:
        p.error("CFG must be nonnegative")
    if min(args.steps, args.slat_steps, args.encoding_views, args.dino_batch_size) < 1:
        p.error("Step/view/batch counts must be positive")
    for name in ("src1", "src2", "ss_checkpoint", "slat_checkpoint", "blender"):
        path = getattr(args, name).expanduser().resolve()
        if not path.is_file():
            p.error(f"Missing {name}: {path}")
        setattr(args, name, path)
    for path in (args.src1, args.src2):
        with path.open("rb") as f:
            if path.suffix.lower() != ".glb" or f.read(4) != b"glTF":
                p.error(f"Expected binary glTF input: {path}")
    args.output_dir = args.output_dir.expanduser().resolve()
    return args


def file_identity(path, digest=False):
    info = {"path": str(path), "bytes": path.stat().st_size, "mtime_ns": path.stat().st_mtime_ns}
    if digest:
        h = hashlib.sha256()
        with path.open("rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                h.update(chunk)
        info["sha256"] = h.hexdigest()
    return info


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2) + "\n")
    tmp.replace(path)


def save_tensor(path, data):
    import torch
    tmp = path.with_suffix(path.suffix + ".tmp")
    torch.save(data, tmp)
    tmp.replace(path)


def sweep(args):
    return list(itertools.product(args.cfg_ss, args.cfg_slat, args.alphas))


def tag(value):
    return format(value, ".8g").replace(".", "p")


def preflight(args):
    import torch
    from huggingface_hub import hf_hub_download
    from eval_validation_latents import detect_flow_target, checkpoint_args
    torch.set_num_threads(int(os.environ.get("OMP_NUM_THREADS", "4")))
    metadata = {}
    for target, path in (("ss", args.ss_checkpoint), ("slat", args.slat_checkpoint)):
        ckpt = torch.load(path, map_location="cpu", weights_only=False, mmap=True)
        cfg = checkpoint_args(ckpt)
        if detect_flow_target(ckpt) != target:
            raise ValueError(f"{path} is not a {target} checkpoint")
        if target == "ss" and cfg.get("ss_flow_arch", "standard") != "standard":
            raise ValueError("This GLB runner requires standard SS, not residual SS")
        if target == "slat" and cfg.get("slat_condition_source", "slat") != "slat":
            raise ValueError("This runner requires SLat-conditioned checkpoints")
        metadata[target] = {"path": str(path), "epoch": ckpt.get("epoch"), "step": ckpt.get("step"),
                            "trellis_prior_weight": cfg.get("trellis_prior_weight", 0)}
        del ckpt
    for model in (ENCODER, SS_DECODER, MESH_DECODER):
        for ext in ("json", "safetensors"):
            path = hf_hub_download(REPO, f"ckpts/{model}.{ext}", local_files_only=args.mode != "prepare")
            print(f"Cache: {path}", flush=True)
    hub = Path(torch.hub.get_dir())
    if args.mode == "prepare":
        enc = torch.hub.load("facebookresearch/dinov2:main", "dinov2_vitl14_reg",
                             pretrained=True, trust_repo=True)
        del enc
    for path in (hub / "facebookresearch_dinov2_main/hubconf.py",
                 hub / "checkpoints/dinov2_vitl14_reg4_pretrain.pth"):
        if not path.is_file():
            raise FileNotFoundError(f"Missing DINO cache; run --mode prepare: {path}")
    subprocess.run([str(args.blender), "--version"], check=True, stdout=subprocess.DEVNULL)
    # Import the actual encoder/decoders now, before requesting GPU computation.
    from encode import TrellisSLatEncoderDebug
    from trellis.models import SLatEncoder, SLatMeshDecoder, SparseStructureDecoder
    print(json.dumps({"checkpoints": metadata, "results": len(sweep(args)),
                      "cfg_ss": args.cfg_ss, "cfg_slat": args.cfg_slat,
                      "alphas": args.alphas, "steps": [args.steps, args.slat_steps]}, indent=2), flush=True)
    return metadata


def encode_asset(args, source, label, encoder):
    import torch
    root = args.output_dir / "encoding" / label
    root.mkdir(parents=True, exist_ok=True)
    identity = {"asset": file_identity(source, digest=True), "views": args.encoding_views,
                "encoder": ENCODER, "feature_model": "dinov2_vitl14_reg", "version": 1}
    cache = root / "slat.pt"
    if cache.is_file():
        saved = torch.load(cache, map_location="cpu", weights_only=True)
        if saved.get("identity") != identity:
            raise ValueError(f"Encoding cache belongs to different input/settings: {root}")
        return saved
    print(f"Encoding {label}: {source} ({args.encoding_views} views)", flush=True)
    latent = encoder.encode_to_slat(str(source), num_views=args.encoding_views,
                                    tmp_dir=str(root), sample_posterior=False)
    if not torch.isfinite(latent.feats).all():
        raise FloatingPointError(f"Non-finite encoded SLat: {source}")
    saved = {"identity": identity, "feats": latent.feats.float().cpu(), "coords": latent.coords.int().cpu()}
    save_tensor(cache, saved)
    return saved


def release():
    import torch
    gc.collect()
    torch.cuda.empty_cache()


def run(args, metadata):
    import numpy as np
    import torch
    from encode import TrellisSLatEncoderDebug
    from trellis.models import from_pretrained
    from eval_validation_latents import (build_model, detect_model_type, load_decoders,
        sample_ss, sample_slat_on_coords, ss_coords_from_latent, decoded_vertex_colors)
    if not torch.cuda.is_available():
        raise RuntimeError("Run this script inside a GPU allocation")
    if args.mixed_precision == "bf16" and not torch.cuda.is_bf16_supported():
        raise RuntimeError("BF16 unsupported; select --mixed-precision fp16 or no")
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    device = torch.device("cuda")
    identity = {k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items() if k != "mode"}
    identity["files"] = [file_identity(p, digest=p.suffix.lower() == ".glb")
                         for p in (args.src1, args.src2, args.ss_checkpoint, args.slat_checkpoint)]
    manifest = args.output_dir / "run.json"
    if manifest.is_file() and json.loads(manifest.read_text())["config"] != identity:
        raise ValueError("Output directory belongs to another run; choose a new --output-dir")
    write_json(manifest, {"config": identity, "checkpoints": metadata, "status": "running",
                         "alpha_convention": "1=src1, 0=src2", "expected_results": len(sweep(args))})
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    encoder = TrellisSLatEncoderDebug(device="cuda", blender_bin=str(args.blender),
                                     dino_batch_size=args.dino_batch_size)
    src1 = encode_asset(args, args.src1, "src1", encoder)
    src2 = encode_asset(args, args.src2, "src2", encoder)
    del encoder
    release()
    batch = {"src1_feats": src1["feats"], "src1_coords": src1["coords"],
             "src2_feats": src2["feats"], "src2_coords": src2["coords"]}

    def load_student(path, target):
        ckpt = torch.load(path, map_location="cpu", weights_only=False, mmap=True)
        model = build_model(ckpt, detect_model_type(ckpt, "auto"), target).to(device).eval()
        model.requires_grad_(False)
        return model

    ss_model = load_student(args.ss_checkpoint, "ss")
    ss_decoder = from_pretrained(f"{REPO}/ckpts/{SS_DECODER}").to(device).eval()
    flow = ss_model.sparse_structure_flow
    target_ss = torch.zeros((1, flow.in_channels, flow.resolution, flow.resolution, flow.resolution), device=device)
    for cfg_ss, alpha in itertools.product(args.cfg_ss, args.alphas):
        path = args.output_dir / "ss" / f"cfg_{tag(cfg_ss)}_alpha_{tag(alpha)}.pt"
        if path.is_file():
            continue
        batch["alpha"] = torch.tensor([alpha])
        torch.manual_seed(args.seed)  # Common SS noise for all alpha/CFG values.
        latent = sample_ss(ss_model, batch, target_ss, args.steps, device, cfg_ss, args.mixed_precision)
        if not torch.isfinite(latent).all():
            raise FloatingPointError(f"Non-finite SS: cfg={cfg_ss}, alpha={alpha}")
        coords = ss_coords_from_latent(ss_decoder, latent, device, args.mixed_precision)
        if not len(coords):
            raise RuntimeError(f"Empty SS coordinates: cfg={cfg_ss}, alpha={alpha}")
        path.parent.mkdir(parents=True, exist_ok=True)
        save_tensor(path, {"latent": latent.cpu(), "coords": coords.cpu()})
        print(f"SS cfg={cfg_ss} alpha={alpha}: {len(coords)} occupied voxels", flush=True)
    del ss_model, ss_decoder, flow, target_ss
    release()
    slat_model = load_student(args.slat_checkpoint, "slat")
    _, mesh_decoder, sparse_cls = load_decoders("slat", device)
    results = []

    def export(feats, coords, path):
        import trimesh
        with torch.no_grad():
            mesh = mesh_decoder(sparse_cls(feats=feats.to(device).float(), coords=coords.to(device).int()))[0]
        if not getattr(mesh, "success", False) or not torch.isfinite(mesh.vertices).all():
            raise RuntimeError(f"Mesh extraction failed: {path}")
        # Blender imported GLB Y-up as internal Z-up. Export back to GLB Y-up,
        # using the same rotation as TRELLIS to_glb(). Preserve vertex colors.
        rotation = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
        vertices = mesh.vertices.detach().float().cpu().numpy() @ rotation
        output = trimesh.Trimesh(vertices=vertices, faces=mesh.faces.cpu().numpy(),
                                 vertex_colors=decoded_vertex_colors(mesh), process=False)
        path.parent.mkdir(parents=True, exist_ok=True)
        output.export(path)
        return {"vertices": len(output.vertices), "faces": len(output.faces)}

    for label, source in (("src1", src1), ("src2", src2)):
        path = args.output_dir / "encoding" / label / "reconstruction.glb"
        if not path.is_file():
            export(source["feats"], source["coords"], path)
    for cfg_ss, cfg_slat, alpha in sweep(args):
        folder = args.output_dir / f"cfg_ss_{tag(cfg_ss)}_slat_{tag(cfg_slat)}" / f"alpha_{tag(alpha)}"
        result_path = folder / "result.json"
        if result_path.is_file() and (folder / "prediction.glb").is_file():
            results.append(json.loads(result_path.read_text()))
            continue
        start = time.monotonic()
        structure = torch.load(args.output_dir / "ss" / f"cfg_{tag(cfg_ss)}_alpha_{tag(alpha)}.pt",
                               map_location="cpu", weights_only=True)
        batch["alpha"] = torch.tensor([alpha])
        torch.manual_seed(args.seed + 1)  # Common SLat noise on identical coords.
        slat = sample_slat_on_coords(slat_model, batch, structure["coords"], args.slat_steps,
                                    device, cfg_slat, args.mixed_precision)
        if slat is None or not torch.isfinite(slat.feats).all():
            raise FloatingPointError(f"Invalid SLat: {folder}")
        folder.mkdir(parents=True, exist_ok=True)
        save_tensor(folder / "slat.pt", {"feats": slat.feats.cpu(), "coords": slat.coords.cpu()})
        geometry = export(slat.feats, slat.coords, folder / "prediction.glb")
        row = {"cfg_ss": cfg_ss, "cfg_slat": cfg_slat, "alpha": alpha,
               "model_alpha": alpha, "ss_steps": args.steps, "slat_steps": args.slat_steps,
               "seconds": time.monotonic() - start, "glb": str(folder / "prediction.glb"), **geometry}
        write_json(result_path, row)
        results.append(row)
        write_json(args.output_dir / "results.json", results)
        print(f"[{len(results)}/{len(sweep(args))}] {row}", flush=True)
        del slat, structure
        release()
    write_json(args.output_dir / "results.json", results)
    write_json(manifest, {"config": identity, "checkpoints": metadata, "status": "complete",
                         "alpha_convention": "1=src1, 0=src2", "expected_results": len(sweep(args)),
                         "completed_results": len(results), "appearance": "decoded vertex colors"})


def main():
    args = parse_args()
    os.environ.setdefault("ATTN_BACKEND", "xformers")
    os.environ.setdefault("SPCONV_ALGO", "native")
    os.environ["HF_HUB_OFFLINE"] = "0" if args.mode == "prepare" else "1"
    metadata = preflight(args)
    if args.mode == "run":
        try:
            run(args, metadata)
        except Exception as exc:
            # Separate failure report preserves the identity of a pre-existing
            # run if the output-directory compatibility check itself fails.
            write_json(args.output_dir / "last_error.json",
                       {"error": type(exc).__name__, "message": str(exc)})
            raise
    else:
        print("CHECK PASSED", flush=True)


if __name__ == "__main__":
    main()
